### PR TITLE
Update to pr13

### LINKED ISSUE #2: Switcher json
Hi!
recently I got an idea of ​​what if I used the Day / Night switch on the page, I mean it would be 23:00 and the page would switch to Night mode and at 7:00 it would be light again.
I am currently using CESIUM and so I would like it to be added, I think people would appreciate it.

Greets Hello.

### LINKED ISSUE #5: Hello
Hello, I need the Staff module for version v2.0 pr 7 of NamelessMC

### PR DESCRIPTION
**Pull request by PadowYT2**
* Make so you can add staff to a panel template
* Deprecated -> new
* Formatting
* i18n

Closes #2 (wrong one), closes #5 (spam), closes #8, closes #9 (due to i18n)

Also, dm Derkades about [translate.namelessmc.com](https://translate.namelessmc.com)
https://cdn.padow.ru/VmWp

### CODE REVIEW

**Review by iAbdullahHassan — APPROVED** [review]

**Comment by tadhgboyle** [comment]
Great work, thanks for doing this Padow 🕺🏼

**Comment by Justman10000** [comment]
@PadowYT2

The module is still not in the weblate

**Comment by Justman10000** [comment]
@Xemah @PadowYT2

No, it is still not in the Weblateinstance

**Comment by PadowYT2** [comment]
> @PadowYT2
> 
> The module is still not in the weblate

> @Xemah @PadowYT2
> 
> No, it is still not in the Weblateinstance

How can I help it??

**Comment by Justman10000** [comment]
> > @PadowYT2
> > The module is still not in the weblate
> 
> > @Xemah @PadowYT2
> > No, it is still not in the Weblateinstance
> 
> How can I help it??

You came with that PR?

**Comment by PadowYT2** [comment]
> > > @PadowYT2
> > > The module is still not in the weblate
> > 
> > 
> > > @Xemah @PadowYT2
> > > No, it is still not in the Weblateinstance
> > 
> > 
> > How can I help it??
> 
> You came with that PR?

I'm not the creator of the module nor admin of the website

**Comment by Justman10000** [comment]
> > > > @PadowYT2
> > > > The module is still not in the weblate
> > > 
> > > 
> > > > @Xemah @PadowYT2
> > > > No, it is still not in the Weblateinstance
> > > 
> > > 
> > > How can I help it??
> > 
> > 
> > You came with that PR?
> 
> I'm not the creator of the module nor admin of the website

I know! Only why do you come with this PR and decide on behalf of the creator that he moves to the Weblate instance?

> Also, dm Derkades about [translate.namelessmc.com](https://translate.namelessmc.com)

**Pull request merged**
